version: '3.3'
services:
    envoy:
        build:
            context: envoy
            dockerfile: Dockerfile
        image: npuzzle/envoy
        network_mode: host
        ports:
            - '8080:8080'
            - '9901:9901'

    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        depends_on:
            - "envoy"
        image: npuzzle/server
        network_mode: host
        ports:
            - '9090:9090'

    client:
        build:
            context: client
            dockerfile: Dockerfile
        depends_on:
            - "server"
            - "envoy"
        image: npuzzle/client
        network_mode: host
        ports:
            - '8081:8081'
