version: '3.3'
services:
    envoy:
        build:
            context: .
            dockerfile: envoy.Dockerfile
        image: npuzzle/envoy
        network_mode: host
        ports:
            - '8080:8080'
            - '9901:9901'

    server:
        build:
            context: ../.
            dockerfile: deploy/server.Dockerfile
        depends_on:
            - "envoy"
        image: npuzzle/server
        ports:
            - '9090:9090'

    client:
        build:
            context: ../.
            dockerfile: deploy/client.Dockerfile
        depends_on:
            - "server"
            - "envoy"
        image: npuzzle/client
        ports:
            - '8081:8081'
