// Code generated by protoc-gen-go. DO NOT EDIT.
// source: npuzzle.proto

package npuzzle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4181303827119de, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Handshake struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4181303827119de, []int{1}
}

func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (m *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(m, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Problem struct {
	Heuristic            string   `protobuf:"bytes,1,opt,name=heuristic,proto3" json:"heuristic,omitempty"`
	Search               string   `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Matrix               string   `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4181303827119de, []int{2}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetHeuristic() string {
	if m != nil {
		return m.Heuristic
	}
	return ""
}

func (m *Problem) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Problem) GetMatrix() string {
	if m != nil {
		return m.Matrix
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "npuzzle.Empty")
	proto.RegisterType((*Handshake)(nil), "npuzzle.Handshake")
	proto.RegisterType((*Problem)(nil), "npuzzle.Problem")
}

func init() { proto.RegisterFile("npuzzle.proto", fileDescriptor_a4181303827119de) }

var fileDescriptor_a4181303827119de = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2b, 0x28, 0xad,
	0xaa, 0xca, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd8, 0xb9,
	0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0x54, 0xb9, 0x38, 0x3d, 0x12, 0xf3, 0x52, 0x8a, 0x33,
	0x12, 0xb3, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0xa5, 0x70, 0x2e, 0xf6, 0x80, 0xa2, 0xfc, 0xa4, 0x9c,
	0xd4, 0x5c, 0x21, 0x19, 0x2e, 0xce, 0x8c, 0xd4, 0xd2, 0xa2, 0xcc, 0xe2, 0x92, 0xcc, 0x64, 0xa8,
	0x32, 0x84, 0x80, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x6a, 0x62, 0x51, 0x72, 0x86, 0x04, 0x13, 0x58,
	0x0a, 0xca, 0x03, 0x89, 0xe7, 0x26, 0x96, 0x14, 0x65, 0x56, 0x48, 0x30, 0x43, 0xc4, 0x21, 0x3c,
	0xa3, 0x2c, 0x2e, 0x76, 0xf7, 0xa2, 0xd4, 0xd4, 0x92, 0xd4, 0x22, 0x21, 0x23, 0x2e, 0x36, 0x30,
	0xb3, 0x58, 0x48, 0x48, 0x0f, 0xe6, 0x6c, 0xb8, 0xdb, 0xa4, 0xb0, 0x88, 0x29, 0x31, 0x08, 0x69,
	0x73, 0xb1, 0x06, 0xe7, 0xe7, 0x94, 0xa5, 0x0a, 0x09, 0xc0, 0xa5, 0xa1, 0xee, 0x94, 0xe2, 0x83,
	0x8b, 0x40, 0x7c, 0xca, 0x90, 0xc4, 0x06, 0x0e, 0x04, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x49, 0x16, 0x9e, 0x2b, 0x15, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	Greets(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*Handshake, error)
	Solve(ctx context.Context, in *Problem, opts ...grpc.CallOption) (*Empty, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Greets(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (*Handshake, error) {
	out := new(Handshake)
	err := c.cc.Invoke(ctx, "/npuzzle.Greeter/Greets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Solve(ctx context.Context, in *Problem, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/npuzzle.Greeter/Solve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	Greets(context.Context, *Handshake) (*Handshake, error)
	Solve(context.Context, *Problem) (*Empty, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) Greets(ctx context.Context, req *Handshake) (*Handshake, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greets not implemented")
}
func (*UnimplementedGreeterServer) Solve(ctx context.Context, req *Problem) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Greets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handshake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Greets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/npuzzle.Greeter/Greets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Greets(ctx, req.(*Handshake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Problem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/npuzzle.Greeter/Solve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Solve(ctx, req.(*Problem))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "npuzzle.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greets",
			Handler:    _Greeter_Greets_Handler,
		},
		{
			MethodName: "Solve",
			Handler:    _Greeter_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npuzzle.proto",
}
